export { default as Header } from './header/Header';
export { default as HomeBanner } from './home-banner/HomeBanner';
export { default as HomeContent } from './home-content/HomeContent';
export { default as LodgingCard } from './home-lodging-card/LodgingCard';
export { default as AboutBanner } from './about-banner/AboutBanner';
export { default as AboutContent } from './about-content/AboutContent';
export { default as Footer } from './footer/Footer';
export { default as NotFound } from './not-found/NotFound';
export { default as Accordion } from './accordion/Accordion';